### ISSUE TITLE
rpi not seeing device as usb?

### ISSUE THREAD

**Issue by skywo1f** [AlexFWulff/awulff-pico-playground#1]
So at the end of your guide, you say I should be able to see the outputs from the pico over usb. but looking at /dev/ nothing new is coming up. Also Thonny is not seeing any devices either. How am I supposed to see the outputs of the pico?

**Comment by skywo1f** [comment]
Even the arduino ide fails to see it under any ports

**Comment by AlexFWulff** [comment]
What operating system are you using?

**Comment by skywo1f** [comment]
I am on the rpi os

**Comment by skywo1f** [comment]
but my windows pc also fails to see this device

**Comment by AlexFWulff** [comment]
Ok - one thing to check is if you're using a USB cable that supports data. Some only have power connections, which might explain why you're having issues

**Comment by skywo1f** [comment]
I know it does data because it is also the same usb I am using it to transfer the file over once I compile it

**Comment by skywo1f** [comment]
do you know what baud rate I should be expecting usb messages at?

**Comment by skywo1f** [comment]
also the pico is blinking quickly, so I assume the code got on there ok. It's seems like it is just not opening up a serial connection on its end

**Comment by skywo1f** [comment]
ok I figured it out. pico-sdk needs to be fully downloaded from github. this means you gotta do 

git submodule update --init

in order to get tinyusb. Then just listen at 9600 baud on ttyACM0
