### ISSUE TITLE
Inferencing without the Neopixels

### ISSUE THREAD

**Issue by Pypico** [AlexFWulff/awulff-pico-playground#2]
Hi @AlexFWulff,
I read your tutorial and it's honestly one of the few that actually clears concept about the inferencing rather than just doing stuff in the code.
I am trying to use your model to design an inference. It will make a certain pin high when a particular keyword is spoken, rest of the hardware is same (mic and pico).
Can you please tell me how should I go with it, just make the pin high when the state is changed? Do I need to use the second core for that?
Thanks.

**Comment by AlexFWulff** [comment]
Yup you shouldn't need the other core for that. You can just stick the line to turn on and off the pin in the if statements where I check the model output and leave everything else the same. You could strip out the code that controls the lighting to reduce the compile time, but everything will work with it still in there.

**Comment by Pypico** [comment]
Great, I'll try it. Thanks.
